---
output:
  pdf_document:
    includes:
      in_header: src/report_subfiles/import.tex
      before_body: src/report_subfiles/before_body.tex

bibliography: src/report_subfiles/references.bib
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.align = "center")
```


\newpage
<!-- (Introduction) -->
# Introduction
??

## Goal
??

## Theory
??


\newpage
<!-- (Methods) -->
# Methods
https://github.com/Vincent-Talen/Project-Machine-Learning-Part1_Analysis  
https://github.com/Vincent-Talen/Project-Machine-Learning-Part2_Java-Wrapper


\newpage
<!-- (Results) -->
# Results
## Data acquisition and preprocessing
??

## Validation and performance
??

## Research findings
??


\newpage
<!-- (Discussion and Conclusion) -->
# Discussion and Conclusion
## Discussion
??

## General conclusion and perspective
??


<!-- (After-Body) -->
```{r after body, child = 'src/report_subfiles/after_body.Rmd'}
```